### ISSUE TITLE
Unable to use AWS Quickstart on Windows 10

### ISSUE THREAD

**Issue by mrethers** [rancher/quickstart#134] opened 2020-10-27 15:44 UTC
Steps to reproduce (least amount of steps as possible):
Follow the steps on AWS quickstart doc

Result:
Failed running cluster err:[Failed to create Certificates deployer container on host [18.207.137.140]: Failed to create Docker container [cert-deployer] on host [18.207.137.140]: Error response from daemon: create /etc/kubernetes: "\/etc/kubernetes" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path]
on ..\rancher-common\rke.tf line 4, in resource "rke_cluster" "rancher_cluster":
4: resource "rke_cluster" "rancher_cluster" {

Environment information
Windows 10
Terraform 0.13.5
Using rancher quickstart commit 453ba69c0c813599941a4b28a1b55f77a75b585c (latest)

This is a follow-up to this thread, but the answer is not helpful as it relates to a different repository:

https://github.com/rancher/rancher/issues/29682

which in turn refers to:

https://github.com/rancher/terraform-provider-rke/issues/248#issuecomment-705015987

**Comment by superseb** [comment] 2020-10-27 16:17
Its a Terraform plugin that is used, as configured here: https://github.com/rancher/quickstart/blob/master/rancher-common/versions.tf#L21. The linked comment confirmed that using 1.1.3 versus the current 1.1.2 fixed the issue. If you can confirm this fixes your issue, we can update this repository.

**Comment by nikkelma** [comment] 2020-10-27 18:41
Just merged #135 to address this issue - `rancher/rke` v1.1.3 should provide the fix as mentioned above, I'll wait for feedback before closing.

**Comment by mrethers** [comment] 2020-10-27 20:53
That did it indeed. I ran into an issue the first time around but I doubt this was related:

>terraform apply --auto-approve
tls_private_key.global_key: Refreshing state... [id=67b8751dae4217bad748d9cfe6e366dbe2754392]
local_file.ssh_public_key_openssh: Refreshing state... [id=b6c15596a995c06b5b589fd756d6a8fc9f2d58e5]
local_file.ssh_private_key_pem: Refreshing state... [id=8d95e198b13eb12c51ff8b2ccde4ba0a654233a5]
aws_key_pair.quickstart_key_pair: Refreshing state... [id=quickstart-rancher-20201021212939425600000001]
data.aws_ami.ubuntu: Refreshing state... [id=ami-00ddb0e5626798373]
aws_security_group.rancher_sg_allowall: Refreshing state... [id=sg-026c50b6bbd8e1397]
aws_instance.rancher_server: Refreshing state... [id=i-0ed3bb68d28ea39f7]
module.rancher_common.rke_cluster.rancher_cluster: Refreshing state... [id=d2d8b99d-2c9a-46c8-bf02-7a89045c7021]
module.rancher_common.local_file.kube_config_server_yaml: Refreshing state... [id=7d1f5e19895740c262054d5a1635fbc0675e07c8]
module.rancher_common.k8s_manifest.cert_manager_crds[1]: Refreshing state... [id=::apiextensions.k8s.io/v1beta1::CustomResourceDefinition::orders.acme.cert-manager.io]
module.rancher_common.k8s_manifest.cert_manager_crds[2]: Refreshing state... [id=::apiextensions.k8s.io/v1beta1::CustomResourceDefinition::certificaterequests.cert-manager.io]
module.rancher_common.k8s_manifest.cert_manager_crds[3]: Refreshing state... [id=::apiextensions.k8s.io/v1beta1::CustomResourceDefinition::certificates.cert-manager.io]
module.rancher_common.k8s_manifest.cert_manager_crds[4]: Refreshing state... [id=::apiextensions.k8s.io/v1beta1::CustomResourceDefinition::challenges.acme.cert-manager.io]
module.rancher_common.k8s_manifest.cert_manager_crds[0]: Refreshing state... [id=::apiextensions.k8s.io/v1beta1::CustomResourceDefinition::issuers.cert-manager.io]
module.rancher_common.k8s_manifest.cert_manager_crds[5]: Refreshing state... [id=::apiextensions.k8s.io/v1beta1::CustomResourceDefinition::clusterissuers.cert-manager.io]
module.rancher_common.helm_release.cert_manager: Creating...

Error: failed to download "https://charts.jetstack.io/charts/cert-manager-v0.15.1.tgz" (hint: running `helm repo update` may help)

  on ..\rancher-common\helm.tf line 4, in resource "helm_release" "cert_manager":
   4: resource "helm_release" "cert_manager" {

**Comment by nikkelma** [comment] 2020-10-30 22:31
Looks like this issue could now be a duplicate of #127 - closing since the original issue was solved, we can move to 127 for further investigation since it seems this is a problem across clouds.

**Closed by nikkelma** 2020-10-30 22:31 UTC
