### ISSUE TITLE
Failed to download (Helm) Cert Manager in AWS

### ISSUE THREAD

**Issue by muralidigi** [rancher/quickstart#214] opened 2022-09-14 04:43 UTC
Hi,

I was testing this in AWS after modified aws_access_key, aws_secret_key, rancher_server_admin_password in terraform.tfvars: 

terraform version 1.2.9 on MacOS

terraform apply fail with the following error:
module.rancher_common.helm_release.cert_manager: Creating...
╷
│ Error: could not download chart: failed to download "https://charts.jetstack.io/charts/cert-manager-v1.7.1.tgz"
│
│   with module.rancher_common.helm_release.cert_manager,
│   on ../rancher-common/helm.tf line 4, in resource "helm_release" "cert_manager":
│    4: resource "helm_release" "cert_manager" {

Any Pointers or help is very much appreciated.

Regards,
Murali

**Comment by bashofmann** [comment] 2022-09-14 10:13
Duplicate of https://github.com/rancher/quickstart/issues/206

**Closed by bashofmann** 2022-09-14 10:13 UTC
