### ISSUE TITLE
worked fine with 1 node, changed to 3 nodes in config.yml, it seems to  be stuck at provisioning

### ISSUE THREAD

**Issue by kundeng** [rancher/quickstart#50] opened 2019-11-19 00:51 UTC
I changed the config.yml to have 3 nodes. vagrant up provisions 4 servers. 

https://172.22.101.101/g/clusters 
 shows the cluster in provisioning status, but it seems to be stuck. 

I vagrant ssh into one of the nodes,  how do I check what is wrong?

**Comment by H8to** [comment] 2020-04-09 12:13
Same here. Is this an IP clash issue? There is only one IP for node, but the count can be `n`?

**Comment by nikkelma** [comment] 2020-05-07 17:45
The Vagrantfile increments the node's IP up from the base `node` IP for further nodes, see [this line in the Vagrantfile](https://github.com/rancher/quickstart/blob/d8d51b17dcc4edba567b22746924d86dae45b58d/vagrant/Vagrantfile#L46).

Tested a 3-node downstream cluster today and worked - I set `k8s_version` to `v1.16.9-rancher1-1` (to guarantee I avoided #53) and set `node.count` to `3` and was successful, hope this is helpful in some way.

**Comment by kundeng** [comment] 2020-05-18 14:38
Were you using virtualbox for vagrant? What exactly did you change beyond setting k8s_version.

**Comment by nikkelma** [comment] 2020-05-18 15:53
I used virtualbox for vagrant on my Mac, and I only changed the two fields I mentioned in `config.yaml`. Can you spin up a fresh vagrant quickstart to see if it works? Could be a good idea to ensure the old vagrant deployment is fully destroyed, too.

**Comment by bashofmann** [comment] 2022-08-26 16:03
Closing, because it does not seem to be reproducible. Please re-open with more details if this is still an issue.

**Closed by bashofmann** 2022-08-26 16:03 UTC
