### ISSUE TITLE
rke_cluster.rancher_cluste creation failing because of etcd

### ISSUE THREAD

**Issue by kitkatneko** [rancher/quickstart#67] opened 2020-04-18 02:41 UTC
I am testing against Azure.... with Terraform v0.12.24
created an SP for Rancher and modified tfvars accordingly.
also installed RKE for my platform

```
terraform providers
.
├── provider.azurerm ~> 2.0.0
└── module.rancher_common
    ├── provider.helm ~> 1.0
    ├── provider.kubernetes 1.10.0
    ├── provider.local ~> 1.4
    ├── provider.rancher2.admin ~> 1.7
    ├── provider.rancher2.bootstrap ~> 1.7
    └── provider.rke 0.14.1
```

as per the module folder

```
> ls .\.terraform\plugins\windows_amd64\
\azure\.terraform\plugins\windows_amd64

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
------       2020-04-17   9:20 PM       51515904 terraform-provider-kubernetes_v1.10.0_x4.exe
------       2020-04-17   9:20 PM       49622528 terraform-provider-helm_v1.1.1_x4.exe
------       2020-04-17   9:21 PM      124372992 terraform-provider-azurerm_v2.0.0_x5.exe
------       2020-04-17   9:22 PM       31506432 terraform-provider-rancher2_v1.8.3_x4.exe
------       2020-04-17   9:22 PM       22242304 terraform-provider-local_v1.4.0_x4.exe
------       2020-04-17   9:42 PM            483 lock.json
------       2019-08-21   4:24 AM       48482816 terraform-provider-rke_v0.14.1.exe
```

terraform init gives the green light.
terraform apply starts but fails on the creation of the rks_cluster with this error:

module.rancher_common.rke_cluster.rancher_cluster: Creating...

```
Error:
Cluster must have at least one etcd plane host: please specify one or more etcd in cluster config


```
 Just after creating that first server:

```
azurerm_virtual_network.rancher-quickstart: Creating...
azurerm_public_ip.rancher-server-pip: Creating...
azurerm_public_ip.quickstart-node-pip: Creating...
azurerm_public_ip.rancher-server-pip: Creation complete after 1s [id=/subscriptions/x-104d-45a1-a02e-x/resourceGroups/quickstart-rancher-quickstart-rg/providers/Microsoft.Network/publicIPAddresses/rancher-server-pip]
azurerm_public_ip.quickstart-node-pip: Creation complete after 1s [id=/subscriptions/x-104d-45a1-a02e-x/resourceGroups/quickstart-rancher-quickstart-rg/providers/Microsoft.Network/publicIPAddresses/quickstart-node-pip]
azurerm_virtual_network.rancher-quickstart: Still creating... [10s elapsed]
azurerm_virtual_network.rancher-quickstart: Creation complete after 11s [id=/subscriptions/x-104d-45a1-a02e-x/resourceGroups/quickstart-rancher-quickstart-rg/providers/Microsoft.Network/virtualNetworks/quickstart-network]
azurerm_subnet.rancher-quickstart-internal: Creating...
azurerm_subnet.rancher-quickstart-internal: Creation complete after 1s [id=/subscriptions/x-104d-45a1-a02e-x/resourceGroups/quickstart-rancher-quickstart-rg/providers/Microsoft.Network/virtualNetworks/quickstart-network/subnets/rancher-quickstart-internal]
azurerm_network_interface.rancher-server-interface: Creating...
azurerm_network_interface.quickstart-node-interface: Creating...
azurerm_network_interface.quickstart-node-interface: Creation complete after 1s [id=/subscriptions/x-104d-45a1-a02e-x/resourceGroups/quickstart-rancher-quickstart-rg/providers/Microsoft.Network/networkInterfaces/quickstart-node-interface]
azurerm_network_interface.rancher-server-interface: Creation complete after 2s [id=/subscriptions/x-104d-45a1-a02e-x/resourceGroups/quickstart-rancher-quickstart-rg/providers/Microsoft.Network/networkInterfaces/rancher-quickstart-interface]
azurerm_linux_virtual_machine.rancher_server: Creating...
azurerm_linux_virtual_machine.rancher_server: Still creating... [10s elapsed]
azurerm_linux_virtual_machine.rancher_server: Provisioning with 'remote-exec'...
azurerm_linux_virtual_machine.rancher_server (remote-exec): Connecting to remote host via SSH...
azurerm_linux_virtual_machine.rancher_server (remote-exec):   Host: x
azurerm_linux_virtual_machine.rancher_server (remote-exec):   User: ubuntu
azurerm_linux_virtual_machine.rancher_server (remote-exec):   Password: false
azurerm_linux_virtual_machine.rancher_server (remote-exec):   Private key: true
azurerm_linux_virtual_machine.rancher_server (remote-exec):   Certificate: false
azurerm_linux_virtual_machine.rancher_server (remote-exec):   SSH Agent: false
azurerm_linux_virtual_machine.rancher_server (remote-exec):   Checking Host Key: false
azurerm_linux_virtual_machine.rancher_server (remote-exec): Connected!
azurerm_linux_virtual_machine.rancher_server (remote-exec): status: done
azurerm_linux_virtual_machine.rancher_server: Creation complete after 2m42s [id=/subscriptions/x-104d-45a1-a02e-x/resourceGroups/quickstart-rancher-quickstart-rg/providers/Microsoft.Compute/virtualMachines/quickstart-rancher-server]
module.rancher_common.rke_cluster.rancher_cluster: Creating...

Error:
Cluster must have at least one etcd plane host: please specify one or more etcd in cluster config

============= RKE outputs ==============

[info] Tearing down Kubernetes cluster
[info] [dialer] Setup tunnel for host [x]
[warning] Failed to set up SSH tunneling for host [x]: Can't initiate NewClient: protocol not available
[warning] Removing host [x] from node lists
[info] Initiating Kubernetes cluster
[info] [dialer] Setup tunnel for host [x]
[warning] Failed to set up SSH tunneling for host [x]: Can't initiate NewClient: protocol not available
[warning] Removing host [x] from node lists
[warning] [state] can't fetch legacy cluster state from Kubernetes
[info] [certificates] Generating CA kubernetes certificates
[info] [certificates] Generating Kubernetes API server aggregation layer requestheader client CA certificates
[info] [certificates] Generating Kube Proxy certificates
[info] [certificates] Generating Kubernetes API server proxy client certificates
[info] [certificates] Generating Kube Controller certificates
[info] [certificates] Generating Kube Scheduler certificates
[info] [certificates] Generating Node certificate
[info] [certificates] Generating admin certificates and kubeconfig
[info] [certificates] Generating Kubernetes API server certificates
[info] Successfully Deployed state file at [\azure\terraform-provider-rke-252231970/cluster.rkestate]  
[info] Building Kubernetes cluster

========================================


  on ..\rancher-common\rke.tf line 4, in resource "rke_cluster" "rancher_cluster":
   4: resource "rke_cluster" "rancher_cluster" {
```

This is pretty much out of the box... what is missing on that new server that is not taken care of by the creation code?

**Comment by shpwrck** [comment] 2020-04-20 13:27
Similar to [this issue](https://github.com/rancher/quickstart/issues/59), there is an issue with creating ssh connections directly from Windows.

The `v1` release of the rke terraform provider will resolve this issue, but until then the proven workaround is to run this command from the windows subsystem using the linux provider.

**Comment by kitkatneko** [comment] 2020-04-20 14:58
looks like the same indeed. I'll start that again from the WSL :)

**Comment by nikkelma** [comment] 2020-05-07 16:25
@kitkatneko Is this resolved, or do you need any more help?

I plan to leave this issue open until either a) docs are updated indicating this limitation or b) a newer version of the RKE provider is used, fixing the root cause.

**Comment by nikkelma** [comment] 2020-06-05 23:18
Version 1.0.0 of `terraform-provider-rke` is now being used, and I've confirmed the quickstart can be successfully deployed from a native Windows environment. I'll close this issue for now, but please re-open if the issue isn't fixed on your end.

**Closed by nikkelma** 2020-06-05 23:18 UTC
