### ISSUE TITLE
Error: Timeout, Rancher is not ready: <nil>

### ISSUE THREAD

**Issue by rrigoni** [rancher/quickstart#64] opened 2020-04-03 17:37 UTC
Getting this issue when applying terraform quickstar for DO. 

Any thoughts? 

```
➜  do git:(master) ✗ terraform apply --auto-approve
digitalocean_ssh_key.quickstart_ssh_key: Refreshing state... [id=27022084]
digitalocean_droplet.rancher_server: Refreshing state... [id=187249495]
module.rancher_common.data.helm_repository.rancher_stable: Refreshing state...
module.rancher_common.data.helm_repository.rancher_latest: Refreshing state...
module.rancher_common.data.helm_repository.jetstack: Refreshing state...

Error: Timeout, Rancher is not ready: <nil>

  on ../rancher-common/provider.tf line 44, in provider "rancher2":
  44: provider "rancher2" {


```

**Comment by rrigoni** [comment] 2020-04-03 19:42
I'm using version `version = "~> 1.7"`  . Any plans on merging that PR?

**Comment by rrigoni** [comment] 2020-04-03 20:16
Ok, I pulled your changes in that PR and now It is showing it is not able to fetch cert-manager-crd. 


```
digitalocean_ssh_key.quickstart_ssh_key: Refreshing state... [id=27022421]
digitalocean_droplet.rancher_server: Refreshing state... [id=187253844]
module.rancher_common.rke_cluster.rancher_cluster: Refreshing state... [id=198.199.88.72]
module.rancher_common.local_file.kube_config_server_yaml: Refreshing state... [id=2e71f81eabdb54176cf2bfb2b3001767df520fe0]
module.rancher_common.data.helm_repository.rancher_latest: Refreshing state...
module.rancher_common.data.helm_repository.jetstack: Refreshing state...
module.rancher_common.data.helm_repository.rancher_stable: Refreshing state...
module.rancher_common.kubernetes_service_account.cert_manager_crd: Refreshing state... [id=kube-system/cert-manager-crd]

Error: Get http://localhost/api/v1/namespaces/kube-system/serviceaccounts/cert-manager-crd: dial tcp [::1]:80: connect: connection refused
```

**Comment by rrigoni** [comment] 2020-04-03 21:05
Ok, I pulled your changes and now there is an issue with Helm downloading rancher. 

```
module.rancher_common.helm_release.cert_manager: Still creating... [1m30s elapsed]
module.rancher_common.helm_release.cert_manager: Still creating... [1m40s elapsed]
module.rancher_common.helm_release.cert_manager: Creation complete after 1m50s [id=cert-manager]
module.rancher_common.helm_release.rancher_server: Creating...

Error: failed to download "rancher-latest/rancher" (hint: running `helm repo update` may help)

  on ../rancher-common/helm.tf line 19, in resource "helm_release" "rancher_server":
  19: resource "helm_release" "rancher_server" {


```

**Comment by mathishaloy** [comment] 2020-04-07 08:26
Getting the same issue when applying terraform quickstar for AWS.

**Comment by AlphaWong** [comment] 2020-04-07 15:31
> Getting this issue when applying terraform quickstar for DO.
> 
> Any thoughts?
> 
> ```
> ➜  do git:(master) ✗ terraform apply --auto-approve
> digitalocean_ssh_key.quickstart_ssh_key: Refreshing state... [id=27022084]
> digitalocean_droplet.rancher_server: Refreshing state... [id=187249495]
> module.rancher_common.data.helm_repository.rancher_stable: Refreshing state...
> module.rancher_common.data.helm_repository.rancher_latest: Refreshing state...
> module.rancher_common.data.helm_repository.jetstack: Refreshing state...
> 
> Error: Timeout, Rancher is not ready: <nil>
> 
>   on ../rancher-common/provider.tf line 44, in provider "rancher2":
>   44: provider "rancher2" {
> ```

same here. but I pull the master branch already

**Comment by rawmind0** [comment] 2020-04-09 10:09
The problem with Rancher2 provider is just with version v1.8.2 due to low retries by default. v1.8.1 is working fine. Anyway, v1.8.3 is being released today and should address the issue.

**Comment by nikkelma** [comment] 2020-06-05 18:25
Has this been resolved? Want to make sure the PRs that have been merged for terraform provider versions fix the issues.

**Comment by dennybritz** [comment] 2020-06-13 17:49
Not sure if this is the same issues, but I am still getting timeouts, but for cert_manager:

```
module.rancher_common.helm_release.cert_manager: Still creating... [4m30s elapsed]
module.rancher_common.helm_release.cert_manager: Still creating... [4m40s elapsed]
module.rancher_common.helm_release.cert_manager: Still creating... [4m50s elapsed]
module.rancher_common.helm_release.cert_manager: Still creating... [5m0s elapsed] 
module.rancher_common.helm_release.cert_manager: Still creating... [5m10s elapsed]
module.rancher_common.helm_release.cert_manager: Still creating... [5m20s elapsed]
module.rancher_common.helm_release.cert_manager: Still creating... [5m30s elapsed]
module.rancher_common.helm_release.cert_manager: Still creating... [5m40s elapsed]
                                                                                  
Error: timed out waiting for the condition                                        
                                                                                  
  on ../rancher-common/helm.tf line 4, in resource "helm_release" "cert_manager": 
   4: resource "helm_release" "cert_manager" {      
```

**Comment by nikkelma** [comment] 2020-06-15 16:06
To confirm, running the same terraform script around roughly the same time where the only difference was `1.7.3` vs `1.8.3` for the rancher terraform provider saw success with 1.7.3 but this timeout for 1.8.3? I ask because we've been seeing some issues installing cert-manager due to its dependency on quay.io and some downtime experienced by that registry, so wanted to make sure that wasn't the root cause.

**Comment by dennybritz** [comment] 2020-06-15 16:14
> To confirm, running the same terraform script around roughly the same time where the only difference was `1.7.3` vs `1.8.3` for the rancher terraform provider saw success with 1.7.3 but this timeout for 1.8.3?

Yep, that's what happened. quay.io downtime could've been the cause, but it seems unlikely because I tried 3-4 times with `1.8.3`, and right after I switched to `1.7.3.` and it worked.

**Comment by nikkelma** [comment] 2020-06-15 16:35
Very interesting, thanks for this info - I'll dig deeper into why exactly this is happening when using GCE.

**Comment by nikkelma** [comment] 2020-08-27 21:38
In many testing runs with GCE I wasn't able to reproduce this, especially since we've moved to Terraform version 0.13 and `rancher2` provider version 1.10. Closing this issue for now, but please reopen if similar issues are seen with Terraform 0.13 and `rancher2` >=1.10.

**Closed by nikkelma** 2020-08-27 21:38 UTC

**Comment by VishalSharma94** [comment] 2020-11-25 15:39
@nikkelma I'm getting the same error as @dennybritz was facing

> timeout issue for cert-manager

This is on `AWS` and `rancher2`version is 1.10.4

**Comment by todori438** [comment] 2020-12-29 09:34
Had similar issue, but it was failing on the certificate part.

module.rancher_common.helm_release.cert_manager: Creating...

Error: failed to download "https://charts.jetstack.io/charts/cert-manager-v1.0.4.tgz" (hint: running `helm repo update` may help)

  on ..\rancher-common\helm.tf line 4, in resource "helm_release" "cert_manager":
   4: resource "helm_release" "cert_manager" {

Got it sorted with updating helm from 2.16 to 3.4.2 and updating the repository
