### ISSUE TITLE
 RKE version is not supported in GCP quickstart

### ISSUE THREAD

**Issue by paologallinaharbur** [rancher/quickstart#193] opened 2021-12-21 13:14 UTC
It seems that the out of the box configuration is currently broken:

```
│ Error: RKE version is not supported [v1.21.7-rancher1-1 v1.21.6-rancher1-2 v1.20.13-rancher1-1 v1.20.12-rancher1-1 v1.20.11-rancher1-2 v1.20.10-rancher1-2 v1.20.5-rancher1-1 v1.20.4-rancher1-1 v1.19.16-rancher1-1 v1.19.15-rancher1-2 v1.19.15-rancher1-1 v1.19.14-rancher1-1 v1.19.13-rancher1-1 v1.19.10-rancher1-1 v1.19.9-rancher1-1 v1.19.8-rancher1-1 v1.19.2-rancher1-1 v1.18.20-rancher1-3 v1.18.20-rancher1-2 v1.18.20-rancher1-1 v1.18.17-rancher1-3 v1.18.17-rancher1-1 v1.18.16-rancher1-2 v1.18.15-rancher1-3 v1.18.14-rancher1-1 v1.18.10-rancher1-1 v1.18.6-rancher1-1 v1.18.3-rancher2-2 v1.17.17-rancher2-4 v1.17.17-rancher2-3 v1.17.17-rancher2-2 v1.17.16-rancher1-2 v1.17.14-rancher1-1 v1.17.13-rancher1-2 v1.17.13-rancher1-1 v1.17.12-rancher1-1 v1.17.11-rancher1-1 v1.17.9-rancher1-2 v1.17.9-rancher1-1 v1.17.6-rancher2-1 v1.17.5-rancher1-1 v1.17.3-rancher1-1 v1.16.15-rancher1-4 v1.16.15-rancher1-3 v1.16.15-rancher1-2 v1.16.15-rancher1-1 v1.16.14-rancher1-1 v1.16.13-rancher1-2 v1.16.13-rancher1-1 v1.16.10-rancher2-2 v1.16.8-rancher1-2 v1.16.7-rancher1-1 v1.16.6-rancher1-2 v1.16.6-rancher1-1 v1.16.4-rancher1-1 v1.16.3-rancher1-1 v1.16.2-rancher1-1 v1.16.1-rancher1-1 v1.15.12-rancher2-7 v1.15.12-rancher2-6 v1.15.12-rancher2-5 v1.15.12-rancher2-4 v1.15.12-rancher2-3 v1.15.12-rancher2-2 v1.15.11-rancher1-3 v1.15.11-rancher1-1 v1.15.11-rancher1-0 v1.15.9-rancher1-1 v1.15.6-rancher1-2 v1.15.5-rancher2-2 v1.15.5-rancher1-2 v1.15.5-rancher1-1 v1.15.4-rancher1-2 v1.15.3-rancher1-1 v1.14.10-rancher1-1 v1.14.6-rancher1-1 v1.14.3-rancher1-1 v1.14.1-rancher1-2 v1.13.12-rancher2-1 v1.13.12-rancher1-1 v1.13.11-rancher1-1 v1.13.10-rancher1-1 v1.13.9-rancher1-1 v1.13.7-rancher1-1 v1.13.5-rancher1-2 v1.13.5-rancher1-1 v1.13.4-rancher1-2 v1.13.4-rancher1-1 v1.13.1-rancher1-1 v1.12.10-rancher1-2 v1.12.10-rancher1-1 v1.12.9-rancher1-1 v1.12.7-rancher1-2 v1.12.7-rancher1-1 v1.12.6-rancher1-2 v1.12.6-rancher1-1 v1.12.5-rancher1-1 v1.12.4-rancher1-1 v1.12.3-rancher1-1 v1.12.1-rancher1-1 v1.12.0-rancher1-1 v1.11.9-rancher1-3 v1.11.9-rancher1-2 v1.11.9-rancher1-1 v1.11.8-rancher1-1 v1.11.6-rancher1-1 v1.11.2-rancher1-2 v1.11.2-rancher1-1 v1.11.1-rancher1-1 v1.10.12-rancher1-1 v1.10.11-rancher1-1 v1.10.5-rancher1-1 v1.10.1-rancher2-1 v1.9.7-rancher2-2 v1.9.7-rancher2-1 v1.9.5-rancher1-1 v1.8.11-rancher2-1] got v1.20.6-rancher1-1
```

Changing the value to one of those seems fixing the issue

**Comment by bashofmann** [comment] 2022-01-03 13:27
This occasionally happened for me as well, but I never really could get to the bottom of it. I can't reproduce this anymore with the update to Rancher 2.6.3 though (https://github.com/rancher/quickstart/commit/5548dc7ea6b4fc25d68f99d366bdcce45f060ef9).

Can you retest this again with the latest version?

**Comment by acwwat** [comment] 2022-01-11 20:39
I think this is related to the problem described in #196 as well.

**Comment by bashofmann** [comment] 2022-01-12 16:28
Closing in favor of https://github.com/rancher/quickstart/issues/196.

**Closed by bashofmann** 2022-01-12 16:28 UTC
